* hangul-s3p2
Emacs Shin Se-beol P2 Input Method, 신세벌식 P2 입력기

두가지 버전이 존재한다. 하나는 hangul.el 방식을 그대로 따른 것이고, 다른 하나는 음절이 완성될 때마다
반환하는 방식이다. 전자는 master 브랜치이고 후자는 letitreturn 브랜치이다.

hangul.el 방식은 무한루프를 돌면서 음절이 만들어져도 반환하지 않는다. 음절의 완성이 다음 음절의 자모에
의해서 결정되기 때문에 이것이 최선의 방법인 것 같다. 그런데 input-method-function은 반환해야 한다고 
문서에 나와 있는 것 같다. 그리고 보통의 사용에서는 문제가 없지만 exwm-xim 같은, input-method-function을
이용하는 기능에서 문제가 생긴다. 그래서 반환하도록 고쳐서 letitreturn 브랜치에 두었다.

* 신세벌식 P2 자판
https://pat.im/1136
** 특징
- 첫가끝 갈마들이 방식
- 기호 확장
- 공세벌식 자판과 비슷한 배열

* 연습
꿈★은 이루어진다
《세종실록》『지리지』
낮 기온 21℃
봄→여름→가을→겨울
감마(γ)선, 제타(ζ) 함수

서시
윤동주

죽는 날까지 하늘을 우러러
한 점 부끄럼이 없기를,
잎새에 이는 바람에도
나는 괴로워했다.
별을 노래하는 마음으로
모든 죽어 가는 것을 사랑해야지
그리고 나한테 주어진 길을
걸어가야겠다.

오늘 밤에도 별이 바람에 스치운다.

꽃
김춘수

내가 그의 이름을 불러주기 전에는
그는 다만
하나의 몸짓에 지나지 않았다.

내가 그의 이름을 불러주었을 때,
그는 나에게로 와서
꽃이 되었다.

내가 그의 이름을 불러준 것처럼
나의 이 빛깔과 향기에 알맞는
누가 나의 이름을 불러다오.

그에게로 가서 나도
그의 꽃이 되고 싶다.

우리들은 모두
무엇이 되고 싶다.

너는 나에게 나는 너에게
잊혀지지 않는
하나의 눈짓이 되고 싶다.

향수
정지용

넓은 벌 동쪽 끝으로
옛이야기 지줄대는 실개천이 회돌아 나가고,
얼룩백이 황소가
해설피 금빛 게으른 울음을 우는 곳,
그곳이 차마 꿈엔들 잊힐 리야.

질화로에 재가 식어지면
비인 밭에 밤바람 소리 말을 달리고,
엷은 졸음에 겨운 늙으신 아버지가
짚베개를 돋아 고이시는 곳,
그곳이 차마 꿈엔들 잊힐 리야.

흙에서 자란 내 마음
파아란 하늘빛이 그리워
함부로 쏜 화살을 찾으려
풀섶 이슬에 함추름 휘적시던 곳,
그곳이 차마 꿈엔들 잊힐 리야.

전설(傳說)바다에 춤추는 밤물결 같은
검은 귀밑머리 날리는 어린 누이와
아무렇지도 않고 예쁠 것도 없는
사철 발 벗은 아내가
따가운 햇살을 등에 지고 이삭 줍던 곳,
그곳이 차마 꿈엔들 잊힐 리야.

하늘에는 성근 별
알 수도 없는 모래성으로 발을 옮기고,
서리 까마귀 우지짖고 지나가는 초라한 지붕,
흐릿한 불빛에 돌아앉아 도란도란거리는 곳,
그곳이 차마 꿈엔들 잊힐 리야.

너에게 묻는다
안도현

연탄재 함부로 발로 차지 마라
너는
누구에게 한번이라도 뜨거운 사람이었느냐

반쯤 깨진 연탄
안도현

언젠가는 나도 활활 타오르고 싶을 것이다
나를 끝 닿는데까지 한번 밀어붙여 보고 싶을 것이다
타고 왔던 트럭에 다시 실려 돌아가면
연탄, 처음으로 붙여진 나의 이름도 으깨어져
나의 존재도 까마득히 뭉개질 터이니
죽어도 여기서 찬란한 끝장을 보고 싶을 것이다
나를 기다리고 있는 찬란한 밑불위에
지금은 인정머리없는 차가운 내 몸을 얹고
아랫쪽부터 불이 건너와 옮겨 붙기를
시간의 바통을 내가 넘겨 받는 순간이 오기를
그리하여 서서히 온몸이 벌겋게 달아오르기를
나도 느껴보고 싶은 것이다
나도 보고 싶은 것이다
모두들 잠든 깊은 밤에 눈에 빨갛게 불을 켜고
구들장 속이 얼마나 침침한지 손을 뻗어보고 싶은 것이다
나로 하여 푸근한 잠 자는 처녀의 등허리를
밤새도록 슬금슬금 만져도 보고 싶은 것이다

거꾸로 강을 거슬러 오르는 저 힘찬 연어들처럼
강산에

흐르는 강물을 거꾸로 거슬러 오르는 연어들의
도무지 알 수 없는 그들만의 신비한 이유처럼
그 언제서부터인가 걸어 걸어 걸어 오는 이길
앞으로 얼마나 더 많이 가야만 하는지

여러 갈랫길 중 만약에 이길이 내가 걸어가고 있는
돌아서 갈 수밖에 없는 꼬부라진 길일지라도
딱딱해지는 발바닥 걸어 걸어 걸어 가다보면
저 넓은 꽃밭에 누워서 난 쉴 수 있겠지

여러 갈랫길 중 만약에 이길이 내가 걸어가고 있는
막막한 어둠으로 별빛조차 없는 길일지라도
포기할 순 없는 거야 걸어 걸어 걸어 가다보면
뜨겁게 날 위해 부서진 햇살을 보겠지

그래도 나에겐 너무나도 많은 축복이란 걸 알아
수없이 많은 걸어가야 할 내 앞길이 있지 않나
그래 다시 가다보면 걸어 걸어 걸어 가다보면
어느날 그 모든 일들을 감사해 하겠지

보이지도 않는 끝
지친 어깨 떨구고 한숨짓는 그대 두려워 말아요
거꾸로 강을 거슬러 오르는 저 힘찬 연어들처럼
걸어 가다 보면 걸어 가다 보면 걸어 가다 보면

기억의 습작
김동률

이젠 버틸 순 없다고
휑한 웃음으로 내 어깨에 기대어 눈을 감았지만
이젠 말할 수 있는 걸
너의 슬픈 눈빛이 나의 마음을 아프게 하는 걸
나에게 말해봐

너의 마음 속으로 들어가 볼 수만 있다면
철없던 나의 모습이 얼만큼 의미가 될 수 있는지

많은 날이 지나고 나의 마음 지쳐 갈 때
내 마음 속으로 스러져 가는 너의 기억이 다시 찾아와
생각이 나겠지
너무 커버린 미래의 그 꿈들 속으로
잊혀져 가는 너의 기억이 다시 생각날까

너의 마음 속으로 들어가 볼 수만 있다면
철없던 나의 모습이 얼만큼 의미가 될 수 있는지

많은 날이 지나고 나의 마음 지쳐갈 때
내 마음 속으로 스러져가는 너의 기억이 다시 찾아와
생각이 나겠지
너무 커버린 내 미래의 그 꿈들 속으로
잊혀져 가는 나의 기억이 다시 생각날까

많은 날이 지나고

나인 너에게
김윤아

그리워했던 목소리마저
사라져 버렸네 모두 떠났네
달콤했었던 그 기대까지
꿈처럼 아득해 흔적조차 없네
끝없이 긴 외로움 그 맘 알아
꼭 삼켜야 했었던 기도까지
모진 하루에 다 지쳐버린
부서진 너를 내가 안아줄게
꾹 다문 입술 불안한 두 손
숨길 수 없는데 홀로 두려운데
차가운 바람이 그친 후엔
아름답게 우리 남을 거야
기억도 아픔도 모두 빛날 거야
끝없이 긴 외로움 그 맘 알아
꼭 삼켜야 했었던 기도까지
모진 하루에 다 지쳐버린
부서진 너를 내가 안아줄게
반드시 나 너를 다시 안아줄게
날 닮은 너를 꼭 다시 안아줄게

